scull: dev is updated ok

diff --git a/device-drivers/src/scull_load b/device-drivers/src/scull_load
--- a/device-drivers/src/scull_load
+++ b/device-drivers/src/scull_load
@@ -4,6 +4,13 @@ module="scull"
 device="scull"
 mode="664"
 
+modprobe -r $device
+#if [ $? -ne 0 ] ; then 
+#    echo "Failed to unload $device..." ; 
+#
+#    exit 1; 
+#fi
+
 # Group: since distributions do it differently, look for wheel or use staff
 if grep -q '^staff:' /etc/group; then
     group="staff"
@@ -14,9 +21,9 @@ fi
 # invoke insmod with all arguments we got
 # and use a pathname, as insmod doesn't look in . by default
 #/sbin/insmod ./$module.ko $* || exit 1
-modprobe $module || exit 1
 
 # retrieve major number
+modprobe $module $major || exit 1
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 echo "major No: $major"
 
